version: "3.8"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: spectral-backend
    expose:
      - "5001"
    ports:
      - "5001:5001" # Keep for direct API testing if needed
    volumes:
      - spectral_data:/app/Spectral_data/Data
      # - ./back-end:/app

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: spectral-frontend
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  spectral_data:
    name: spectral_data
